In [6]:
# importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score,recall_score,f1_score

In [7]:
#importing data files
data_test=pd.read_csv('fraudTest.csv')
data_train=pd.read_csv('fraudTrain.csv')

In [8]:
# seeing test dataset
data_test.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [9]:
#seeing train dataset
data_train.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [13]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [14]:
# Split the training data into features (X_train) and labels (y_train)
# target variable = is_fraud
X_train=data_train.drop('is_fraud',axis=1)
y_train=data_train['is_fraud']

In [15]:
#Split the testing data into features (X_test) and labels (y_test)
X_test=data_test.drop('is_fraud',axis=1)
y_test=data_test['is_fraud']

In [16]:
# Standardize the features
# scaler=StandardScaler()
# X_train=scaler.fit_transform(X_train)
# X_test=scaler.fit_transform(X_test)

# giving error due to non-numeric data

In [17]:
# Exclude non-numeric columns from standardization for training data
numeric_columns=X_train.select_dtypes(include=['number']).columns
X_train_numeric=X_train[numeric_columns]

In [18]:
# exclude non-numeric columns from standardization for testing data
numeric_columns_test=X_test.select_dtypes(include=['number']).columns
X_test_numeric=X_test[numeric_columns_test]

In [19]:
# Now Standardize the feature
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train_numeric)
X_test_scaled=scaler.fit_transform(X_test_numeric)

In [20]:
# Apply SMOTE to the training data
smote=SMOTE(random_state=42)
X_train_resampled,y_train_resampled=smote.fit_resample(X_train_scaled,y_train)

In [ ]:
# fine-tune Random Forest Hyperparameters 
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [ ]:
grid_search = GridSearchCV(RandomForestClassifier(class_weight='balanced', random_state=42), param_grid, cv=3, scoring='f1')
grid_search.fit(X_train_resampled, y_train_resampled)
best_rf_model = grid_search.best_estimator_

In [ ]:
# Access feature importances
feature_importances = best_rf_model.feature_importances_

In [14]:
#Logistic Regression
logistic_model=LogisticRegression()
logistic_model.fit(X_train_scaled,y_train)
logistic_predictions=logistic_model.predict(X_test_scaled)

In [15]:
#Decision Tree
tree_model=DecisionTreeClassifier()
tree_model.fit(X_train_scaled,y_train)
tree_predictions=tree_model.predict(X_test_scaled)

In [ ]:
# Random Forest
forest_model=RandomForestClassifier(n_estimators=100,class_weight='balanced',random_state=42)
forest_model.fit(X_train_resampled,y_train_resampled)
forest_predictions=forest_model.predict(X_test_scaled)

In [17]:
# Evaluate model
def evaluate_model(predictions,model_name):
    accuracy=accuracy_score(y_test,predictions)
    precision=precision_score(y_test,predictions)
    recall=recall_score(y_test,predictions)
    f1=f1_score(y_test,predictions)
    
    print(f"-----{model_name}-----")
    print(f"Accuracy:{accuracy:.4f}")
    print(f"Precision:{precision:.4f}")
    print(f"Recall:{recall:.4f}")
    print(f"F1-score:{f1:.4f}")
    print("\n")

In [18]:
# Evaluate Logistic Regression
evaluate_model(logistic_predictions,"Logistic Regression")

-----Logistic Regression-----
Accuracy:0.9955
Precision:0.0000
Recall:0.0000
F1-score:0.0000

In [19]:
# Evaluate Decision Tree
evaluate_model(tree_predictions,"Decision Tree")

-----Decision Tree-----
Accuracy:0.9797
Precision:0.0451
Recall:0.2112
F1-score:0.0743

In [20]:
# evaluate Random Forest
evaluate_model(forest_predictions,"Random Forest")

-----Random Forest-----
Accuracy:0.9961
Precision:0.3136
Recall:0.0172
F1-score:0.0327

# Conclusion

The Random Forest model, characterized by its high accuracy and substantial precision gains, serves as a robust foundation for fraud detection. Continuous optimization through hyperparameter tuning and advanced techniques is recommended for further enhancing its ability to identify fraudulent transactions effectively